# Generated by Django 5.2.8 on 2025-12-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savednewsarticle',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savednewsarticle',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savednewsarticle',
            name='full_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
