# Generated by Django 5.2.8 on 2025-12-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_page', '0002_savednewsarticle_author_savednewsarticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgalleryitem',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='saved_gallery/media/'),
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='saved_gallery/thumbnails/'),
        ),
    ]
