# Generated by Django 5.2.8 on 2025-12-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_page', '0003_savedgalleryitem_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedgalleryitem',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='savedgalleryitem',
            name='thumbnail_file',
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='media_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='media_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='media_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='thumbnail_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='thumbnail_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedgalleryitem',
            name='thumbnail_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
