# Name of the GitHub Actions workflow
name: CI - Tests & Coverage

# When this workflow should run
on:
  push:
    #branches: [ main, features/space_news]  # Run workflow on push to main branch
  pull_request:
    types: [opened, synchronize, reopened]  # Run workflow for PR events

# Define the jobs that run in this workflow
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner provided by GitHub

    # sets default working dir to orbitstream
    defaults:
      run:
        working-directory: orbitstream

    # Environment variables available to all steps in this job
    env:
      DJANGO_SETTINGS_MODULE: orbitstream.settings  # Django needs this to locate settings.py

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
          pip install -r ../requirements-dev.txt

      # Step 4: Run Django migrations
      - name: Run migrations
        run: |
          python manage.py migrate --noinput || true

      # Step 5: Run tests with coverage
      - name: Running tests
        run: |
          python -m coverage run manage.py test

      # Step 6: Generate coverage data files
      - name: Generate coverage data
        run: |
          python -m coverage xml
          python -m coverage json

      # Step 7: Upload coverage artifacts
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: |
            orbitstream/.coverage
            orbitstream/coverage.xml
            orbitstream/coverage.json